export type Gender = 'girl' | 'boy' | 'unisex';

export type BabyName = {
  name: string;
  gender: Gender;
  meaning: string;
  origin: string;
};

export const NAMES: BabyName[] = [
  // ---- Girls ----
  { name: 'Aaliyah', gender: 'girl', meaning: 'Exalted, sublime', origin: 'Arabic' },
  { name: 'Ava', gender: 'girl', meaning: 'Life; bird', origin: 'Latin' },
  { name: 'Amelia', gender: 'girl', meaning: 'Work, industrious', origin: 'Germanic' },
  { name: 'Aurora', gender: 'girl', meaning: 'Dawn', origin: 'Latin' },
  { name: 'Ayla', gender: 'girl', meaning: 'Moonlight, halo', origin: 'Turkish' },
  { name: 'Bella', gender: 'girl', meaning: 'Beautiful', origin: 'Italian' },
  { name: 'Charlotte', gender: 'girl', meaning: 'Free man', origin: 'French' },
  { name: 'Chloe', gender: 'girl', meaning: 'Blooming, fertility', origin: 'Greek' },
  { name: 'Clara', gender: 'girl', meaning: 'Bright, clear', origin: 'Latin' },
  { name: 'Daisy', gender: 'girl', meaning: "Day's eye, the flower", origin: 'English' },
  { name: 'Delilah', gender: 'girl', meaning: 'Delicate', origin: 'Hebrew' },
  { name: 'Eleanor', gender: 'girl', meaning: 'Bright, shining one', origin: 'Greek' },
  { name: 'Elena', gender: 'girl', meaning: 'Bright, shining light', origin: 'Greek' },
  { name: 'Eliana', gender: 'girl', meaning: 'My God has answered', origin: 'Hebrew' },
  { name: 'Ella', gender: 'girl', meaning: 'Fairy maiden; all', origin: 'Germanic' },
  { name: 'Emma', gender: 'girl', meaning: 'Whole, universal', origin: 'Germanic' },
  { name: 'Esme', gender: 'girl', meaning: 'Esteemed, beloved', origin: 'French' },
  { name: 'Evelyn', gender: 'girl', meaning: 'Wished-for child', origin: 'English' },
  { name: 'Fatima', gender: 'girl', meaning: 'Captivating', origin: 'Arabic' },
  { name: 'Fiona', gender: 'girl', meaning: 'Fair, white', origin: 'Gaelic' },
  { name: 'Freya', gender: 'girl', meaning: 'Lady, noblewoman', origin: 'Norse' },
  { name: 'Grace', gender: 'girl', meaning: 'Grace of God', origin: 'Latin' },
  { name: 'Hana', gender: 'girl', meaning: 'Flower; happiness', origin: 'Japanese' },
  { name: 'Hannah', gender: 'girl', meaning: 'Grace, favor', origin: 'Hebrew' },
  { name: 'Harper', gender: 'girl', meaning: 'Harp player', origin: 'English' },
  { name: 'Hazel', gender: 'girl', meaning: 'The hazelnut tree', origin: 'English' },
  { name: 'Imogen', gender: 'girl', meaning: 'Maiden', origin: 'Celtic' },
  { name: 'Iris', gender: 'girl', meaning: 'Rainbow', origin: 'Greek' },
  { name: 'Isabella', gender: 'girl', meaning: 'Pledged to God', origin: 'Hebrew' },
  { name: 'Isla', gender: 'girl', meaning: 'Island', origin: 'Scottish' },
  { name: 'Ivy', gender: 'girl', meaning: 'The ivy plant; faithfulness', origin: 'English' },
  { name: 'Jasmine', gender: 'girl', meaning: 'Gift from God; the flower', origin: 'Persian' },
  { name: 'Julia', gender: 'girl', meaning: 'Youthful', origin: 'Latin' },
  { name: 'Kira', gender: 'girl', meaning: 'Light; leader', origin: 'Persian' },
  { name: 'Layla', gender: 'girl', meaning: 'Night, dark beauty', origin: 'Arabic' },
  { name: 'Leah', gender: 'girl', meaning: 'Weary; delicate', origin: 'Hebrew' },
  { name: 'Lila', gender: 'girl', meaning: 'Night; play', origin: 'Arabic' },
  { name: 'Lily', gender: 'girl', meaning: 'The lily flower; purity', origin: 'English' },
  { name: 'Luna', gender: 'girl', meaning: 'Moon', origin: 'Latin' },
  { name: 'Maya', gender: 'girl', meaning: 'Illusion; water', origin: 'Sanskrit' },
  { name: 'Mia', gender: 'girl', meaning: 'Mine; beloved', origin: 'Italian' },
  { name: 'Mila', gender: 'girl', meaning: 'Gracious, dear', origin: 'Slavic' },
  { name: 'Mira', gender: 'girl', meaning: 'Ocean; wonderful', origin: 'Sanskrit' },
  { name: 'Naomi', gender: 'girl', meaning: 'Pleasantness', origin: 'Hebrew' },
  { name: 'Nora', gender: 'girl', meaning: 'Light; honor', origin: 'Latin' },
  { name: 'Nova', gender: 'girl', meaning: 'New', origin: 'Latin' },
  { name: 'Olivia', gender: 'girl', meaning: 'Olive tree', origin: 'Latin' },
  { name: 'Penelope', gender: 'girl', meaning: 'Weaver', origin: 'Greek' },
  { name: 'Phoebe', gender: 'girl', meaning: 'Bright, radiant', origin: 'Greek' },
  { name: 'Priya', gender: 'girl', meaning: 'Beloved', origin: 'Sanskrit' },
  { name: 'Quinn', gender: 'girl', meaning: 'Wise, counsel', origin: 'Gaelic' },
  { name: 'Rose', gender: 'girl', meaning: 'The rose flower', origin: 'Latin' },
  { name: 'Ruby', gender: 'girl', meaning: 'Red gemstone', origin: 'Latin' },
  { name: 'Sadie', gender: 'girl', meaning: 'Princess', origin: 'Hebrew' },
  { name: 'Sara', gender: 'girl', meaning: 'Princess', origin: 'Hebrew' },
  { name: 'Scarlett', gender: 'girl', meaning: 'Red', origin: 'English' },
  { name: 'Sienna', gender: 'girl', meaning: 'Reddish-brown; from Siena', origin: 'Italian' },
  { name: 'Sofia', gender: 'girl', meaning: 'Wisdom', origin: 'Greek' },
  { name: 'Stella', gender: 'girl', meaning: 'Star', origin: 'Latin' },
  { name: 'Talia', gender: 'girl', meaning: 'Dew of God; gentle', origin: 'Hebrew' },
  { name: 'Thea', gender: 'girl', meaning: 'Goddess', origin: 'Greek' },
  { name: 'Valentina', gender: 'girl', meaning: 'Strong, healthy', origin: 'Latin' },
  { name: 'Vera', gender: 'girl', meaning: 'Faith; truth', origin: 'Slavic' },
  { name: 'Victoria', gender: 'girl', meaning: 'Victory', origin: 'Latin' },
  { name: 'Violet', gender: 'girl', meaning: 'The violet flower', origin: 'Latin' },
  { name: 'Willow', gender: 'girl', meaning: 'The willow tree; grace', origin: 'English' },
  { name: 'Yasmin', gender: 'girl', meaning: 'Jasmine flower', origin: 'Persian' },
  { name: 'Zara', gender: 'girl', meaning: 'Blooming flower; princess', origin: 'Arabic' },
  { name: 'Zoe', gender: 'girl', meaning: 'Life', origin: 'Greek' },

  // ---- Boys ----
  { name: 'Aaron', gender: 'boy', meaning: 'High mountain; exalted', origin: 'Hebrew' },
  { name: 'Adam', gender: 'boy', meaning: 'Son of the earth', origin: 'Hebrew' },
  { name: 'Adrian', gender: 'boy', meaning: 'From Hadria; dark one', origin: 'Latin' },
  { name: 'Ahmed', gender: 'boy', meaning: 'Highly praised', origin: 'Arabic' },
  { name: 'Aiden', gender: 'boy', meaning: 'Little fire', origin: 'Gaelic' },
  { name: 'Alexander', gender: 'boy', meaning: 'Defender of the people', origin: 'Greek' },
  { name: 'Ali', gender: 'boy', meaning: 'Exalted, noble', origin: 'Arabic' },
  { name: 'Amir', gender: 'boy', meaning: 'Prince, commander', origin: 'Arabic' },
  { name: 'Andrew', gender: 'boy', meaning: 'Strong, manly', origin: 'Greek' },
  { name: 'Arlo', gender: 'boy', meaning: 'Fortified hill', origin: 'English' },
  { name: 'Arthur', gender: 'boy', meaning: 'Bear; noble', origin: 'Celtic' },
  { name: 'Asher', gender: 'boy', meaning: 'Happy, blessed', origin: 'Hebrew' },
  { name: 'Atlas', gender: 'boy', meaning: 'To carry, endure', origin: 'Greek' },
  { name: 'Benjamin', gender: 'boy', meaning: 'Son of the right hand', origin: 'Hebrew' },
  { name: 'Caleb', gender: 'boy', meaning: 'Devotion, whole-hearted', origin: 'Hebrew' },
  { name: 'Charles', gender: 'boy', meaning: 'Free man', origin: 'Germanic' },
  { name: 'Daniel', gender: 'boy', meaning: 'God is my judge', origin: 'Hebrew' },
  { name: 'David', gender: 'boy', meaning: 'Beloved', origin: 'Hebrew' },
  { name: 'Dylan', gender: 'boy', meaning: 'Son of the sea', origin: 'Welsh' },
  { name: 'Eli', gender: 'boy', meaning: 'Ascended, uplifted', origin: 'Hebrew' },
  { name: 'Elias', gender: 'boy', meaning: 'The Lord is my God', origin: 'Hebrew' },
  { name: 'Emir', gender: 'boy', meaning: 'Prince, leader', origin: 'Arabic' },
  { name: 'Ethan', gender: 'boy', meaning: 'Strong, enduring', origin: 'Hebrew' },
  { name: 'Ezra', gender: 'boy', meaning: 'Help, helper', origin: 'Hebrew' },
  { name: 'Felix', gender: 'boy', meaning: 'Happy, fortunate', origin: 'Latin' },
  { name: 'Finn', gender: 'boy', meaning: 'Fair, white', origin: 'Gaelic' },
  { name: 'Gabriel', gender: 'boy', meaning: 'God is my strength', origin: 'Hebrew' },
  { name: 'George', gender: 'boy', meaning: 'Farmer, earth-worker', origin: 'Greek' },
  { name: 'Hassan', gender: 'boy', meaning: 'Handsome, good', origin: 'Arabic' },
  { name: 'Henry', gender: 'boy', meaning: 'Ruler of the home', origin: 'Germanic' },
  { name: 'Hugo', gender: 'boy', meaning: 'Mind, intellect', origin: 'Germanic' },
  { name: 'Ibrahim', gender: 'boy', meaning: 'Father of multitudes', origin: 'Arabic' },
  { name: 'Isaac', gender: 'boy', meaning: 'He will laugh', origin: 'Hebrew' },
  { name: 'Ivan', gender: 'boy', meaning: 'God is gracious', origin: 'Slavic' },
  { name: 'Jack', gender: 'boy', meaning: 'God is gracious', origin: 'English' },
  { name: 'Jacob', gender: 'boy', meaning: 'Supplanter', origin: 'Hebrew' },
  { name: 'James', gender: 'boy', meaning: 'Supplanter', origin: 'Hebrew' },
  { name: 'Julian', gender: 'boy', meaning: 'Youthful, downy', origin: 'Latin' },
  { name: 'Kai', gender: 'boy', meaning: 'Sea', origin: 'Hawaiian' },
  { name: 'Khalid', gender: 'boy', meaning: 'Eternal, immortal', origin: 'Arabic' },
  { name: 'Leo', gender: 'boy', meaning: 'Lion', origin: 'Latin' },
  { name: 'Liam', gender: 'boy', meaning: 'Strong-willed protector', origin: 'Irish' },
  { name: 'Lucas', gender: 'boy', meaning: 'Bringer of light', origin: 'Latin' },
  { name: 'Mateo', gender: 'boy', meaning: 'Gift of God', origin: 'Spanish' },
  { name: 'Max', gender: 'boy', meaning: 'Greatest', origin: 'Latin' },
  { name: 'Micah', gender: 'boy', meaning: 'Who is like God?', origin: 'Hebrew' },
  { name: 'Muhammad', gender: 'boy', meaning: 'Praiseworthy', origin: 'Arabic' },
  { name: 'Nathan', gender: 'boy', meaning: 'He gave', origin: 'Hebrew' },
  { name: 'Noah', gender: 'boy', meaning: 'Rest, comfort', origin: 'Hebrew' },
  { name: 'Oliver', gender: 'boy', meaning: 'Olive tree', origin: 'Latin' },
  { name: 'Omar', gender: 'boy', meaning: 'Flourishing, long-lived', origin: 'Arabic' },
  { name: 'Oscar', gender: 'boy', meaning: 'Deer lover; divine spear', origin: 'Gaelic' },
  { name: 'Owen', gender: 'boy', meaning: 'Young warrior; well-born', origin: 'Welsh' },
  { name: 'Rafael', gender: 'boy', meaning: 'God has healed', origin: 'Hebrew' },
  { name: 'Rayan', gender: 'boy', meaning: "Gates of heaven; watered", origin: 'Arabic' },
  { name: 'Rohan', gender: 'boy', meaning: 'Ascending; sandalwood', origin: 'Sanskrit' },
  { name: 'Roman', gender: 'boy', meaning: 'From Rome', origin: 'Latin' },
  { name: 'Samuel', gender: 'boy', meaning: 'God has heard', origin: 'Hebrew' },
  { name: 'Sebastian', gender: 'boy', meaning: 'Venerable, revered', origin: 'Greek' },
  { name: 'Theodore', gender: 'boy', meaning: 'Gift of God', origin: 'Greek' },
  { name: 'Thomas', gender: 'boy', meaning: 'Twin', origin: 'Aramaic' },
  { name: 'Victor', gender: 'boy', meaning: 'Conqueror', origin: 'Latin' },
  { name: 'William', gender: 'boy', meaning: 'Resolute protector', origin: 'Germanic' },
  { name: 'Yusuf', gender: 'boy', meaning: 'God increases', origin: 'Arabic' },
  { name: 'Zayn', gender: 'boy', meaning: 'Beauty, grace', origin: 'Arabic' },

  // ---- Unisex ----
  { name: 'Alex', gender: 'unisex', meaning: 'Defender of the people', origin: 'Greek' },
  { name: 'Avery', gender: 'unisex', meaning: 'Ruler of elves', origin: 'English' },
  { name: 'Charlie', gender: 'unisex', meaning: 'Free', origin: 'English' },
  { name: 'Eden', gender: 'unisex', meaning: 'Delight, paradise', origin: 'Hebrew' },
  { name: 'Ellis', gender: 'unisex', meaning: 'Benevolent', origin: 'Welsh' },
  { name: 'Emery', gender: 'unisex', meaning: 'Industrious ruler', origin: 'Germanic' },
  { name: 'Frankie', gender: 'unisex', meaning: 'Free one', origin: 'English' },
  { name: 'Jaden', gender: 'unisex', meaning: 'Thankful; God has heard', origin: 'Hebrew' },
  { name: 'Jamie', gender: 'unisex', meaning: 'Supplanter', origin: 'Hebrew' },
  { name: 'Jordan', gender: 'unisex', meaning: 'To flow down', origin: 'Hebrew' },
  { name: 'Kai', gender: 'unisex', meaning: 'Sea', origin: 'Hawaiian' },
  { name: 'Noor', gender: 'unisex', meaning: 'Light', origin: 'Arabic' },
  { name: 'Parker', gender: 'unisex', meaning: 'Park keeper', origin: 'English' },
  { name: 'Reese', gender: 'unisex', meaning: 'Ardor, enthusiasm', origin: 'Welsh' },
  { name: 'River', gender: 'unisex', meaning: 'A flowing body of water', origin: 'English' },
  { name: 'Robin', gender: 'unisex', meaning: 'Bright fame; the bird', origin: 'Germanic' },
  { name: 'Rowan', gender: 'unisex', meaning: 'Little red one; the tree', origin: 'Gaelic' },
  { name: 'Sage', gender: 'unisex', meaning: 'Wise; the herb', origin: 'Latin' },
  { name: 'Sam', gender: 'unisex', meaning: 'God has heard', origin: 'Hebrew' },
  { name: 'Sky', gender: 'unisex', meaning: 'The sky', origin: 'English' },

  // ---- Origin coverage: ensures every origin has at least 10 names ----
  // Aramaic
  { name: 'Martha', gender: 'girl', meaning: 'Lady, mistress', origin: 'Aramaic' },
  { name: 'Tabitha', gender: 'girl', meaning: 'Gazelle', origin: 'Aramaic' },
  { name: 'Talitha', gender: 'girl', meaning: 'Little girl, maiden', origin: 'Aramaic' },
  { name: 'Magdalena', gender: 'girl', meaning: 'Woman of Magdala', origin: 'Aramaic' },
  { name: 'Marta', gender: 'girl', meaning: 'Lady (form of Martha)', origin: 'Aramaic' },
  { name: 'Bartholomew', gender: 'boy', meaning: 'Son of Talmai', origin: 'Aramaic' },
  { name: 'Thaddeus', gender: 'boy', meaning: 'Courageous heart', origin: 'Aramaic' },
  { name: 'Cephas', gender: 'boy', meaning: 'Rock, stone', origin: 'Aramaic' },
  { name: 'Maron', gender: 'boy', meaning: 'Little lord', origin: 'Aramaic' },

  // Irish
  { name: 'Saoirse', gender: 'girl', meaning: 'Freedom, liberty', origin: 'Irish' },
  { name: 'Aoife', gender: 'girl', meaning: 'Beauty, radiance', origin: 'Irish' },
  { name: 'Niamh', gender: 'girl', meaning: 'Bright, radiant', origin: 'Irish' },
  { name: 'Ciara', gender: 'girl', meaning: 'Dark-haired', origin: 'Irish' },
  { name: 'Maeve', gender: 'girl', meaning: 'She who intoxicates', origin: 'Irish' },
  { name: 'Cian', gender: 'boy', meaning: 'Ancient, enduring', origin: 'Irish' },
  { name: 'Cillian', gender: 'boy', meaning: 'Bright-headed; strife', origin: 'Irish' },
  { name: 'Declan', gender: 'boy', meaning: 'Full of goodness', origin: 'Irish' },
  { name: 'Ronan', gender: 'boy', meaning: 'Little seal', origin: 'Irish' },

  // Japanese
  { name: 'Sakura', gender: 'girl', meaning: 'Cherry blossom', origin: 'Japanese' },
  { name: 'Yui', gender: 'girl', meaning: 'Gentle, superior', origin: 'Japanese' },
  { name: 'Aoi', gender: 'girl', meaning: 'Hollyhock; blue', origin: 'Japanese' },
  { name: 'Yuki', gender: 'unisex', meaning: 'Snow; happiness', origin: 'Japanese' },
  { name: 'Akira', gender: 'unisex', meaning: 'Bright, clear', origin: 'Japanese' },
  { name: 'Sora', gender: 'unisex', meaning: 'Sky', origin: 'Japanese' },
  { name: 'Haruki', gender: 'boy', meaning: 'Shining sun; spring child', origin: 'Japanese' },
  { name: 'Hiroshi', gender: 'boy', meaning: 'Generous, prosperous', origin: 'Japanese' },
  { name: 'Ren', gender: 'boy', meaning: 'Lotus; love', origin: 'Japanese' },

  // Norse
  { name: 'Astrid', gender: 'girl', meaning: 'Divinely beautiful', origin: 'Norse' },
  { name: 'Sigrid', gender: 'girl', meaning: 'Beautiful victory', origin: 'Norse' },
  { name: 'Ingrid', gender: 'girl', meaning: 'Beautiful, fair', origin: 'Norse' },
  { name: 'Saga', gender: 'girl', meaning: 'Seeing one; story', origin: 'Norse' },
  { name: 'Erik', gender: 'boy', meaning: 'Eternal ruler', origin: 'Norse' },
  { name: 'Bjorn', gender: 'boy', meaning: 'Bear', origin: 'Norse' },
  { name: 'Leif', gender: 'boy', meaning: 'Heir, descendant', origin: 'Norse' },
  { name: 'Sven', gender: 'boy', meaning: 'Young man', origin: 'Norse' },
  { name: 'Thor', gender: 'boy', meaning: 'Thunder', origin: 'Norse' },

  // Scottish
  { name: 'Skye', gender: 'girl', meaning: 'From the Isle of Skye', origin: 'Scottish' },
  { name: 'Ailsa', gender: 'girl', meaning: 'Elf victory', origin: 'Scottish' },
  { name: 'Maisie', gender: 'girl', meaning: 'Pearl', origin: 'Scottish' },
  { name: 'Lorna', gender: 'girl', meaning: 'From Lorne', origin: 'Scottish' },
  { name: 'Hamish', gender: 'boy', meaning: 'Supplanter (form of James)', origin: 'Scottish' },
  { name: 'Lachlan', gender: 'boy', meaning: 'From the land of lakes', origin: 'Scottish' },
  { name: 'Callum', gender: 'boy', meaning: 'Dove', origin: 'Scottish' },
  { name: 'Rory', gender: 'unisex', meaning: 'Red king', origin: 'Scottish' },
  { name: 'Blair', gender: 'unisex', meaning: 'Plain, field', origin: 'Scottish' },

  // Spanish
  { name: 'Paloma', gender: 'girl', meaning: 'Dove', origin: 'Spanish' },
  { name: 'Dolores', gender: 'girl', meaning: 'Sorrows', origin: 'Spanish' },
  { name: 'Pilar', gender: 'girl', meaning: 'Pillar', origin: 'Spanish' },
  { name: 'Consuelo', gender: 'girl', meaning: 'Consolation', origin: 'Spanish' },
  { name: 'Mercedes', gender: 'girl', meaning: 'Mercies', origin: 'Spanish' },
  { name: 'Santiago', gender: 'boy', meaning: 'Saint James', origin: 'Spanish' },
  { name: 'Diego', gender: 'boy', meaning: 'Supplanter', origin: 'Spanish' },
  { name: 'Javier', gender: 'boy', meaning: 'Bright; new house', origin: 'Spanish' },
  { name: 'Cruz', gender: 'unisex', meaning: 'Cross', origin: 'Spanish' },

  // Turkish
  { name: 'Derya', gender: 'girl', meaning: 'Ocean', origin: 'Turkish' },
  { name: 'Defne', gender: 'girl', meaning: 'Laurel', origin: 'Turkish' },
  { name: 'Selin', gender: 'girl', meaning: 'Flowing water', origin: 'Turkish' },
  { name: 'Yagmur', gender: 'girl', meaning: 'Rain', origin: 'Turkish' },
  { name: 'Deniz', gender: 'unisex', meaning: 'Sea', origin: 'Turkish' },
  { name: 'Emre', gender: 'boy', meaning: 'Friend, beloved', origin: 'Turkish' },
  { name: 'Mert', gender: 'boy', meaning: 'Brave, manly', origin: 'Turkish' },
  { name: 'Kaan', gender: 'boy', meaning: 'King, ruler', origin: 'Turkish' },
  { name: 'Baris', gender: 'boy', meaning: 'Peace', origin: 'Turkish' },

  // Celtic
  { name: 'Bridget', gender: 'girl', meaning: 'Strength; exalted one', origin: 'Celtic' },
  { name: 'Gwen', gender: 'girl', meaning: 'White, fair, blessed', origin: 'Celtic' },
  { name: 'Tegan', gender: 'girl', meaning: 'Fair, lovely', origin: 'Celtic' },
  { name: 'Brenna', gender: 'girl', meaning: 'Raven; little drop', origin: 'Celtic' },
  { name: 'Tristan', gender: 'boy', meaning: 'Tumult; sorrowful', origin: 'Celtic' },
  { name: 'Gareth', gender: 'boy', meaning: 'Gentle', origin: 'Celtic' },
  { name: 'Morgan', gender: 'unisex', meaning: 'Sea-born; sea circle', origin: 'Celtic' },
  { name: 'Kerry', gender: 'unisex', meaning: 'Dark-haired; from Kerry', origin: 'Celtic' },

  // French
  { name: 'Genevieve', gender: 'girl', meaning: 'Tribe woman; white wave', origin: 'French' },
  { name: 'Amelie', gender: 'girl', meaning: 'Hardworking, industrious', origin: 'French' },
  { name: 'Colette', gender: 'girl', meaning: 'Victory of the people', origin: 'French' },
  { name: 'Margaux', gender: 'girl', meaning: 'Pearl', origin: 'French' },
  { name: 'Elodie', gender: 'girl', meaning: 'Foreign riches', origin: 'French' },
  { name: 'Camille', gender: 'unisex', meaning: 'Young ceremonial attendant', origin: 'French' },
  { name: 'Louis', gender: 'boy', meaning: 'Renowned warrior', origin: 'French' },
  { name: 'Remy', gender: 'boy', meaning: 'Oarsman; from Rheims', origin: 'French' },

  // Hawaiian
  { name: 'Leilani', gender: 'girl', meaning: 'Heavenly flowers', origin: 'Hawaiian' },
  { name: 'Kailani', gender: 'girl', meaning: 'Sea and sky', origin: 'Hawaiian' },
  { name: 'Moana', gender: 'girl', meaning: 'Ocean', origin: 'Hawaiian' },
  { name: 'Nalani', gender: 'girl', meaning: 'The heavens', origin: 'Hawaiian' },
  { name: 'Mahina', gender: 'girl', meaning: 'Moon', origin: 'Hawaiian' },
  { name: 'Kalani', gender: 'unisex', meaning: 'The heavens, the sky', origin: 'Hawaiian' },
  { name: 'Keanu', gender: 'boy', meaning: 'Cool mountain breeze', origin: 'Hawaiian' },
  { name: 'Koa', gender: 'boy', meaning: 'Warrior; brave', origin: 'Hawaiian' },

  // Italian
  { name: 'Giulia', gender: 'girl', meaning: 'Youthful', origin: 'Italian' },
  { name: 'Francesca', gender: 'girl', meaning: 'Free one', origin: 'Italian' },
  { name: 'Gianna', gender: 'girl', meaning: 'God is gracious', origin: 'Italian' },
  { name: 'Chiara', gender: 'girl', meaning: 'Bright, clear', origin: 'Italian' },
  { name: 'Leonardo', gender: 'boy', meaning: 'Brave as a lion', origin: 'Italian' },
  { name: 'Marco', gender: 'boy', meaning: 'Warlike; of Mars', origin: 'Italian' },
  { name: 'Lorenzo', gender: 'boy', meaning: 'From Laurentum; laurel', origin: 'Italian' },

  // Persian
  { name: 'Roxana', gender: 'girl', meaning: 'Dawn, bright', origin: 'Persian' },
  { name: 'Soraya', gender: 'girl', meaning: 'The Pleiades', origin: 'Persian' },
  { name: 'Nasrin', gender: 'girl', meaning: 'Wild rose', origin: 'Persian' },
  { name: 'Parisa', gender: 'girl', meaning: 'Like a fairy', origin: 'Persian' },
  { name: 'Darius', gender: 'boy', meaning: 'Possessing goodness', origin: 'Persian' },
  { name: 'Cyrus', gender: 'boy', meaning: 'Sun; lord', origin: 'Persian' },
  { name: 'Arman', gender: 'boy', meaning: 'Hope, aspiration', origin: 'Persian' },

  // Slavic
  { name: 'Nadia', gender: 'girl', meaning: 'Hope', origin: 'Slavic' },
  { name: 'Milena', gender: 'girl', meaning: 'Gracious, dear', origin: 'Slavic' },
  { name: 'Zora', gender: 'girl', meaning: 'Dawn', origin: 'Slavic' },
  { name: 'Anya', gender: 'girl', meaning: 'Grace', origin: 'Slavic' },
  { name: 'Bogdan', gender: 'boy', meaning: 'Given by God', origin: 'Slavic' },
  { name: 'Vladimir', gender: 'boy', meaning: 'Ruler of peace; great power', origin: 'Slavic' },
  { name: 'Boris', gender: 'boy', meaning: 'Fighter', origin: 'Slavic' },

  // Sanskrit
  { name: 'Ananya', gender: 'girl', meaning: 'Unique, incomparable', origin: 'Sanskrit' },
  { name: 'Asha', gender: 'girl', meaning: 'Hope, wish', origin: 'Sanskrit' },
  { name: 'Aarav', gender: 'boy', meaning: 'Peaceful; melodic sound', origin: 'Sanskrit' },
  { name: 'Arjun', gender: 'boy', meaning: 'Bright, shining; white', origin: 'Sanskrit' },
  { name: 'Kiran', gender: 'unisex', meaning: 'Ray of light', origin: 'Sanskrit' },
  { name: 'Ravi', gender: 'boy', meaning: 'Sun', origin: 'Sanskrit' },

  // Welsh
  { name: 'Gwyneth', gender: 'girl', meaning: 'Blessed, happy', origin: 'Welsh' },
  { name: 'Carys', gender: 'girl', meaning: 'Love', origin: 'Welsh' },
  { name: 'Eira', gender: 'girl', meaning: 'Snow', origin: 'Welsh' },
  { name: 'Megan', gender: 'girl', meaning: 'Pearl', origin: 'Welsh' },
  { name: 'Bryn', gender: 'unisex', meaning: 'Hill', origin: 'Welsh' },
  { name: 'Lloyd', gender: 'boy', meaning: 'Grey; sacred', origin: 'Welsh' },

  // Gaelic
  { name: 'Brianna', gender: 'girl', meaning: 'Strong, virtuous, noble', origin: 'Gaelic' },
  { name: 'Sloane', gender: 'unisex', meaning: 'Raider', origin: 'Gaelic' },
  { name: 'Brody', gender: 'boy', meaning: 'Ditch; from Brodie', origin: 'Gaelic' },
  { name: 'Nolan', gender: 'boy', meaning: 'Champion; noble', origin: 'Gaelic' },

  // Germanic
  { name: 'Frieda', gender: 'girl', meaning: 'Peaceful', origin: 'Germanic' },
];

export const ORIGINS = Array.from(new Set(NAMES.map((n) => n.origin))).sort();

export function searchNames(query: string, gender: Gender | 'all', origin: string | 'all'): BabyName[] {
  const q = query.trim().toLowerCase();
  return NAMES.filter((n) => {
    if (gender !== 'all' && n.gender !== gender) return false;
    if (origin !== 'all' && n.origin !== origin) return false;
    if (q && !n.name.toLowerCase().includes(q) && !n.meaning.toLowerCase().includes(q)) return false;
    return true;
  }).sort((a, b) => a.name.localeCompare(b.name));
}