export const babySizes: Record<number, { item: string; emoji: string; length: string; weight: string }> = {
  4:  { item: 'a poppy seed', emoji: '🌱', length: '0.2 cm', weight: '<1 g' },
  5:  { item: 'a sesame seed', emoji: '🌱', length: '0.3 cm', weight: '<1 g' },
  6:  { item: 'a lentil', emoji: '🫘', length: '0.5 cm', weight: '<1 g' },
  7:  { item: 'a blueberry', emoji: '🫐', length: '1 cm', weight: '1 g' },
  8:  { item: 'a raspberry', emoji: '🍓', length: '1.6 cm', weight: '1 g' },
  9:  { item: 'a cherry', emoji: '🍒', length: '2.3 cm', weight: '2 g' },
  10: { item: 'a strawberry', emoji: '🍓', length: '3.1 cm', weight: '4 g' },
  11: { item: 'a lime', emoji: '🍋', length: '4.1 cm', weight: '7 g' },
  12: { item: 'a plum', emoji: '🍑', length: '5.4 cm', weight: '14 g' },
  13: { item: 'a peach', emoji: '🍑', length: '7.4 cm', weight: '23 g' },
  14: { item: 'a lemon', emoji: '🍋', length: '8.7 cm', weight: '43 g' },
  15: { item: 'an apple', emoji: '🍎', length: '10.1 cm', weight: '70 g' },
  16: { item: 'an avocado', emoji: '🥑', length: '11.6 cm', weight: '100 g' },
  17: { item: 'a pear', emoji: '🍐', length: '13 cm', weight: '140 g' },
  18: { item: 'a bell pepper', emoji: '🫑', length: '14.2 cm', weight: '190 g' },
  19: { item: 'a mango', emoji: '🥭', length: '15.3 cm', weight: '240 g' },
  20: { item: 'a banana', emoji: '🍌', length: '25.6 cm', weight: '300 g' },
  21: { item: 'a carrot', emoji: '🥕', length: '26.7 cm', weight: '360 g' },
  22: { item: 'a papaya', emoji: '🥭', length: '27.8 cm', weight: '430 g' },
  23: { item: 'a grapefruit', emoji: '🍊', length: '28.9 cm', weight: '500 g' },
  24: { item: 'an ear of corn', emoji: '🌽', length: '30 cm', weight: '600 g' },
  25: { item: 'a cauliflower', emoji: '🥦', length: '34.6 cm', weight: '660 g' },
  26: { item: 'a lettuce', emoji: '🥬', length: '35.6 cm', weight: '760 g' },
  27: { item: 'a cabbage', emoji: '🥬', length: '36.6 cm', weight: '875 g' },
  28: { item: 'an eggplant', emoji: '🍆', length: '37.6 cm', weight: '1 kg' },
  29: { item: 'a butternut squash', emoji: '🎃', length: '38.6 cm', weight: '1.15 kg' },
  30: { item: 'a cucumber', emoji: '🥒', length: '39.9 cm', weight: '1.3 kg' },
  31: { item: 'a coconut', emoji: '🥥', length: '41.1 cm', weight: '1.5 kg' },
  32: { item: 'a napa cabbage', emoji: '🥬', length: '42.4 cm', weight: '1.7 kg' },
  33: { item: 'a pineapple', emoji: '🍍', length: '43.7 cm', weight: '1.9 kg' },
  34: { item: 'a cantaloupe', emoji: '🍈', length: '45 cm', weight: '2.1 kg' },
  35: { item: 'a honeydew melon', emoji: '🍈', length: '46.2 cm', weight: '2.4 kg' },
  36: { item: 'a romaine lettuce', emoji: '🥬', length: '47.4 cm', weight: '2.6 kg' },
  37: { item: 'a winter melon', emoji: '🍈', length: '48.6 cm', weight: '2.9 kg' },
  38: { item: 'a small pumpkin', emoji: '🎃', length: '49.8 cm', weight: '3.1 kg' },
  39: { item: 'a mini watermelon', emoji: '🍉', length: '50.7 cm', weight: '3.3 kg' },
  40: { item: 'a pumpkin', emoji: '🎃', length: '51.2 cm', weight: '3.5 kg' },
};

export function getBabySize(week: number) {
  const clamped = Math.min(40, Math.max(4, week));
  return babySizes[clamped];
}