export type Gender = 'girl' | 'boy' | 'unisex';

export type BabyName = {
  name: string;
  gender: Gender;
  meaning: string;
  origin: string;
};

export const NAMES: BabyName[] = [
  // ---- Girls ----
  { name: 'Aaliyah', gender: 'girl', meaning: 'Exalted, sublime', origin: 'Arabic' },
  { name: 'Ava', gender: 'girl', meaning: 'Life; bird', origin: 'Latin' },
  { name: 'Amelia', gender: 'girl', meaning: 'Work, industrious', origin: 'Germanic' },
  { name: 'Aurora', gender: 'girl', meaning: 'Dawn', origin: 'Latin' },
  { name: 'Ayla', gender: 'girl', meaning: 'Moonlight, halo', origin: 'Turkish' },
  { name: 'Bella', gender: 'girl', meaning: 'Beautiful', origin: 'Italian' },
  { name: 'Charlotte', gender: 'girl', meaning: 'Free man', origin: 'French' },
  { name: 'Chloe', gender: 'girl', meaning: 'Blooming, fertility', origin: 'Greek' },
  { name: 'Clara', gender: 'girl', meaning: 'Bright, clear', origin: 'Latin' },
  { name: 'Daisy', gender: 'girl', meaning: "Day's eye, the flower", origin: 'English' },
  { name: 'Delilah', gender: 'girl', meaning: 'Delicate', origin: 'Hebrew' },
  { name: 'Eleanor', gender: 'girl', meaning: 'Bright, shining one', origin: 'Greek' },
  { name: 'Elena', gender: 'girl', meaning: 'Bright, shining light', origin: 'Greek' },
  { name: 'Eliana', gender: 'girl', meaning: 'My God has answered', origin: 'Hebrew' },
  { name: 'Ella', gender: 'girl', meaning: 'Fairy maiden; all', origin: 'Germanic' },
  { name: 'Emma', gender: 'girl', meaning: 'Whole, universal', origin: 'Germanic' },
  { name: 'Esme', gender: 'girl', meaning: 'Esteemed, beloved', origin: 'French' },
  { name: 'Evelyn', gender: 'girl', meaning: 'Wished-for child', origin: 'English' },
  { name: 'Fatima', gender: 'girl', meaning: 'Captivating', origin: 'Arabic' },
  { name: 'Fiona', gender: 'girl', meaning: 'Fair, white', origin: 'Gaelic' },
  { name: 'Freya', gender: 'girl', meaning: 'Lady, noblewoman', origin: 'Norse' },
  { name: 'Grace', gender: 'girl', meaning: 'Grace of God', origin: 'Latin' },
  { name: 'Hana', gender: 'girl', meaning: 'Flower; happiness', origin: 'Japanese' },
  { name: 'Hannah', gender: 'girl', meaning: 'Grace, favor', origin: 'Hebrew' },
  { name: 'Harper', gender: 'girl', meaning: 'Harp player', origin: 'English' },
  { name: 'Hazel', gender: 'girl', meaning: 'The hazelnut tree', origin: 'English' },
  { name: 'Imogen', gender: 'girl', meaning: 'Maiden', origin: 'Celtic' },
  { name: 'Iris', gender: 'girl', meaning: 'Rainbow', origin: 'Greek' },
  { name: 'Isabella', gender: 'girl', meaning: 'Pledged to God', origin: 'Hebrew' },
  { name: 'Isla', gender: 'girl', meaning: 'Island', origin: 'Scottish' },
  { name: 'Ivy', gender: 'girl', meaning: 'The ivy plant; faithfulness', origin: 'English' },
  { name: 'Jasmine', gender: 'girl', meaning: 'Gift from God; the flower', origin: 'Persian' },
  { name: 'Julia', gender: 'girl', meaning: 'Youthful', origin: 'Latin' },
  { name: 'Kira', gender: 'girl', meaning: 'Light; leader', origin: 'Persian' },
  { name: 'Layla', gender: 'girl', meaning: 'Night, dark beauty', origin: 'Arabic' },
  { name: 'Leah', gender: 'girl', meaning: 'Weary; delicate', origin: 'Hebrew' },
  { name: 'Lila', gender: 'girl', meaning: 'Night; play', origin: 'Arabic' },
  { name: 'Lily', gender: 'girl', meaning: 'The lily flower; purity', origin: 'English' },
  { name: 'Luna', gender: 'girl', meaning: 'Moon', origin: 'Latin' },
  { name: 'Maya', gender: 'girl', meaning: 'Illusion; water', origin: 'Sanskrit' },
  { name: 'Mia', gender: 'girl', meaning: 'Mine; beloved', origin: 'Italian' },
  { name: 'Mila', gender: 'girl', meaning: 'Gracious, dear', origin: 'Slavic' },
  { name: 'Mira', gender: 'girl', meaning: 'Ocean; wonderful', origin: 'Sanskrit' },
  { name: 'Naomi', gender: 'girl', meaning: 'Pleasantness', origin: 'Hebrew' },
  { name: 'Nora', gender: 'girl', meaning: 'Light; honor', origin: 'Latin' },
  { name: 'Nova', gender: 'girl', meaning: 'New', origin: 'Latin' },
  { name: 'Olivia', gender: 'girl', meaning: 'Olive tree', origin: 'Latin' },
  { name: 'Penelope', gender: 'girl', meaning: 'Weaver', origin: 'Greek' },
  { name: 'Phoebe', gender: 'girl', meaning: 'Bright, radiant', origin: 'Greek' },
  { name: 'Priya', gender: 'girl', meaning: 'Beloved', origin: 'Sanskrit' },
  { name: 'Quinn', gender: 'girl', meaning: 'Wise, counsel', origin: 'Gaelic' },
  { name: 'Rose', gender: 'girl', meaning: 'The rose flower', origin: 'Latin' },
  { name: 'Ruby', gender: 'girl', meaning: 'Red gemstone', origin: 'Latin' },
  { name: 'Sadie', gender: 'girl', meaning: 'Princess', origin: 'Hebrew' },
  { name: 'Sara', gender: 'girl', meaning: 'Princess', origin: 'Hebrew' },
  { name: 'Scarlett', gender: 'girl', meaning: 'Red', origin: 'English' },
  { name: 'Sienna', gender: 'girl', meaning: 'Reddish-brown; from Siena', origin: 'Italian' },
  { name: 'Sofia', gender: 'girl', meaning: 'Wisdom', origin: 'Greek' },
  { name: 'Stella', gender: 'girl', meaning: 'Star', origin: 'Latin' },
  { name: 'Talia', gender: 'girl', meaning: 'Dew of God; gentle', origin: 'Hebrew' },
  { name: 'Thea', gender: 'girl', meaning: 'Goddess', origin: 'Greek' },
  { name: 'Valentina', gender: 'girl', meaning: 'Strong, healthy', origin: 'Latin' },
  { name: 'Vera', gender: 'girl', meaning: 'Faith; truth', origin: 'Slavic' },
  { name: 'Victoria', gender: 'girl', meaning: 'Victory', origin: 'Latin' },
  { name: 'Violet', gender: 'girl', meaning: 'The violet flower', origin: 'Latin' },
  { name: 'Willow', gender: 'girl', meaning: 'The willow tree; grace', origin: 'English' },
  { name: 'Yasmin', gender: 'girl', meaning: 'Jasmine flower', origin: 'Persian' },
  { name: 'Zara', gender: 'girl', meaning: 'Blooming flower; princess', origin: 'Arabic' },
  { name: 'Zoe', gender: 'girl', meaning: 'Life', origin: 'Greek' },

  // ---- Boys ----
  { name: 'Aaron', gender: 'boy', meaning: 'High mountain; exalted', origin: 'Hebrew' },
  { name: 'Adam', gender: 'boy', meaning: 'Son of the earth', origin: 'Hebrew' },
  { name: 'Adrian', gender: 'boy', meaning: 'From Hadria; dark one', origin: 'Latin' },
  { name: 'Ahmed', gender: 'boy', meaning: 'Highly praised', origin: 'Arabic' },
  { name: 'Aiden', gender: 'boy', meaning: 'Little fire', origin: 'Gaelic' },
  { name: 'Alexander', gender: 'boy', meaning: 'Defender of the people', origin: 'Greek' },
  { name: 'Ali', gender: 'boy', meaning: 'Exalted, noble', origin: 'Arabic' },
  { name: 'Amir', gender: 'boy', meaning: 'Prince, commander', origin: 'Arabic' },
  { name: 'Andrew', gender: 'boy', meaning: 'Strong, manly', origin: 'Greek' },
  { name: 'Arlo', gender: 'boy', meaning: 'Fortified hill', origin: 'English' },
  { name: 'Arthur', gender: 'boy', meaning: 'Bear; noble', origin: 'Celtic' },
  { name: 'Asher', gender: 'boy', meaning: 'Happy, blessed', origin: 'Hebrew' },
  { name: 'Atlas', gender: 'boy', meaning: 'To carry, endure', origin: 'Greek' },
  { name: 'Benjamin', gender: 'boy', meaning: 'Son of the right hand', origin: 'Hebrew' },
  { name: 'Caleb', gender: 'boy', meaning: 'Devotion, whole-hearted', origin: 'Hebrew' },
  { name: 'Charles', gender: 'boy', meaning: 'Free man', origin: 'Germanic' },
  { name: 'Daniel', gender: 'boy', meaning: 'God is my judge', origin: 'Hebrew' },
  { name: 'David', gender: 'boy', meaning: 'Beloved', origin: 'Hebrew' },
  { name: 'Dylan', gender: 'boy', meaning: 'Son of the sea', origin: 'Welsh' },
  { name: 'Eli', gender: 'boy', meaning: 'Ascended, uplifted', origin: 'Hebrew' },
  { name: 'Elias', gender: 'boy', meaning: 'The Lord is my God', origin: 'Hebrew' },
  { name: 'Emir', gender: 'boy', meaning: 'Prince, leader', origin: 'Arabic' },
  { name: 'Ethan', gender: 'boy', meaning: 'Strong, enduring', origin: 'Hebrew' },
  { name: 'Ezra', gender: 'boy', meaning: 'Help, helper', origin: 'Hebrew' },
  { name: 'Felix', gender: 'boy', meaning: 'Happy, fortunate', origin: 'Latin' },
  { name: 'Finn', gender: 'boy', meaning: 'Fair, white', origin: 'Gaelic' },
  { name: 'Gabriel', gender: 'boy', meaning: 'God is my strength', origin: 'Hebrew' },
  { name: 'George', gender: 'boy', meaning: 'Farmer, earth-worker', origin: 'Greek' },
  { name: 'Hassan', gender: 'boy', meaning: 'Handsome, good', origin: 'Arabic' },
  { name: 'Henry', gender: 'boy', meaning: 'Ruler of the home', origin: 'Germanic' },
  { name: 'Hugo', gender: 'boy', meaning: 'Mind, intellect', origin: 'Germanic' },
  { name: 'Ibrahim', gender: 'boy', meaning: 'Father of multitudes', origin: 'Arabic' },
  { name: 'Isaac', gender: 'boy', meaning: 'He will laugh', origin: 'Hebrew' },
  { name: 'Ivan', gender: 'boy', meaning: 'God is gracious', origin: 'Slavic' },
  { name: 'Jack', gender: 'boy', meaning: 'God is gracious', origin: 'English' },
  { name: 'Jacob', gender: 'boy', meaning: 'Supplanter', origin: 'Hebrew' },
  { name: 'James', gender: 'boy', meaning: 'Supplanter', origin: 'Hebrew' },
  { name: 'Julian', gender: 'boy', meaning: 'Youthful, downy', origin: 'Latin' },
  { name: 'Kai', gender: 'boy', meaning: 'Sea', origin: 'Hawaiian' },
  { name: 'Khalid', gender: 'boy', meaning: 'Eternal, immortal', origin: 'Arabic' },
  { name: 'Leo', gender: 'boy', meaning: 'Lion', origin: 'Latin' },
  { name: 'Liam', gender: 'boy', meaning: 'Strong-willed protector', origin: 'Irish' },
  { name: 'Lucas', gender: 'boy', meaning: 'Bringer of light', origin: 'Latin' },
  { name: 'Mateo', gender: 'boy', meaning: 'Gift of God', origin: 'Spanish' },
  { name: 'Max', gender: 'boy', meaning: 'Greatest', origin: 'Latin' },
  { name: 'Micah', gender: 'boy', meaning: 'Who is like God?', origin: 'Hebrew' },
  { name: 'Muhammad', gender: 'boy', meaning: 'Praiseworthy', origin: 'Arabic' },
  { name: 'Nathan', gender: 'boy', meaning: 'He gave', origin: 'Hebrew' },
  { name: 'Noah', gender: 'boy', meaning: 'Rest, comfort', origin: 'Hebrew' },
  { name: 'Oliver', gender: 'boy', meaning: 'Olive tree', origin: 'Latin' },
  { name: 'Omar', gender: 'boy', meaning: 'Flourishing, long-lived', origin: 'Arabic' },
  { name: 'Oscar', gender: 'boy', meaning: 'Deer lover; divine spear', origin: 'Gaelic' },
  { name: 'Owen', gender: 'boy', meaning: 'Young warrior; well-born', origin: 'Welsh' },
  { name: 'Rafael', gender: 'boy', meaning: 'God has healed', origin: 'Hebrew' },
  { name: 'Rayan', gender: 'boy', meaning: "Gates of heaven; watered", origin: 'Arabic' },
  { name: 'Rohan', gender: 'boy', meaning: 'Ascending; sandalwood', origin: 'Sanskrit' },
  { name: 'Roman', gender: 'boy', meaning: 'From Rome', origin: 'Latin' },
  { name: 'Samuel', gender: 'boy', meaning: 'God has heard', origin: 'Hebrew' },
  { name: 'Sebastian', gender: 'boy', meaning: 'Venerable, revered', origin: 'Greek' },
  { name: 'Theodore', gender: 'boy', meaning: 'Gift of God', origin: 'Greek' },
  { name: 'Thomas', gender: 'boy', meaning: 'Twin', origin: 'Aramaic' },
  { name: 'Victor', gender: 'boy', meaning: 'Conqueror', origin: 'Latin' },
  { name: 'William', gender: 'boy', meaning: 'Resolute protector', origin: 'Germanic' },
  { name: 'Yusuf', gender: 'boy', meaning: 'God increases', origin: 'Arabic' },
  { name: 'Zayn', gender: 'boy', meaning: 'Beauty, grace', origin: 'Arabic' },

  // ---- Unisex ----
  { name: 'Alex', gender: 'unisex', meaning: 'Defender of the people', origin: 'Greek' },
  { name: 'Avery', gender: 'unisex', meaning: 'Ruler of elves', origin: 'English' },
  { name: 'Charlie', gender: 'unisex', meaning: 'Free', origin: 'English' },
  { name: 'Eden', gender: 'unisex', meaning: 'Delight, paradise', origin: 'Hebrew' },
  { name: 'Ellis', gender: 'unisex', meaning: 'Benevolent', origin: 'Welsh' },
  { name: 'Emery', gender: 'unisex', meaning: 'Industrious ruler', origin: 'Germanic' },
  { name: 'Frankie', gender: 'unisex', meaning: 'Free one', origin: 'English' },
  { name: 'Jaden', gender: 'unisex', meaning: 'Thankful; God has heard', origin: 'Hebrew' },
  { name: 'Jamie', gender: 'unisex', meaning: 'Supplanter', origin: 'Hebrew' },
  { name: 'Jordan', gender: 'unisex', meaning: 'To flow down', origin: 'Hebrew' },
  { name: 'Kai', gender: 'unisex', meaning: 'Sea', origin: 'Hawaiian' },
  { name: 'Noor', gender: 'unisex', meaning: 'Light', origin: 'Arabic' },
  { name: 'Parker', gender: 'unisex', meaning: 'Park keeper', origin: 'English' },
  { name: 'Reese', gender: 'unisex', meaning: 'Ardor, enthusiasm', origin: 'Welsh' },
  { name: 'River', gender: 'unisex', meaning: 'A flowing body of water', origin: 'English' },
  { name: 'Robin', gender: 'unisex', meaning: 'Bright fame; the bird', origin: 'Germanic' },
  { name: 'Rowan', gender: 'unisex', meaning: 'Little red one; the tree', origin: 'Gaelic' },
  { name: 'Sage', gender: 'unisex', meaning: 'Wise; the herb', origin: 'Latin' },
  { name: 'Sam', gender: 'unisex', meaning: 'God has heard', origin: 'Hebrew' },
  { name: 'Sky', gender: 'unisex', meaning: 'The sky', origin: 'English' },
];

export const ORIGINS = Array.from(new Set(NAMES.map((n) => n.origin))).sort();

export function searchNames(query: string, gender: Gender | 'all', origin: string | 'all'): BabyName[] {
  const q = query.trim().toLowerCase();
  return NAMES.filter((n) => {
    if (gender !== 'all' && n.gender !== gender) return false;
    if (origin !== 'all' && n.origin !== origin) return false;
    if (q && !n.name.toLowerCase().includes(q) && !n.meaning.toLowerCase().includes(q)) return false;
    return true;
  }).sort((a, b) => a.name.localeCompare(b.name));
}